name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_map: ^4.0.0
  latlong2: ^0.8.1
  webview_flutter: ^2.0.14
  cupertino_icons: ^1.0.6
  get:
  flutter_native_splash: ^2.4.0
  firebase_core: ^2.32.0
  firebase_auth: ^4.19.0
  cloud_firestore: ^4.17.2
  intl: ^0.19.0
  provider: ^6.0.0
  http: ^0.13.6
  flutter_spinkit: ^5.2.1
  image_picker: ^1.1.1
  firebase_storage: ^11.7.4
  pdf: ^3.10.8
  path_provider: ^2.1.3
  open_document: ^1.0.7
  firebase_app_check: ^0.2.2+7
  dio: ^5.4.3+1
  fl_chart: ^0.68.0
  flutter_localizations:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  shared_preferences: ^2.2.3
  geolocator: ^12.0.0
  permission_handler: ^10.3.0
  url_launcher: ^6.1.14
  bottom_sheet: ^4.0.0
  flutter_staggered_animations: ^1.1.1

dependency_overrides:
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mockito: ^5.3.0
  build_runner: ^2.1.2

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/fonts/roboto/Roboto-Regular.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/keybas_logo.png"