// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJoXk7jRHaQcUdZggsL7Xjf48osBd9VTo',
    appId: '1:1023285541885:web:ba5836f2b96df7ad9db794',
    messagingSenderId: '1023285541885',
    projectId: 'mctruckcheck',
    authDomain: 'mctruckcheck.firebaseapp.com',
    storageBucket: 'mctruckcheck.appspot.com',
    measurementId: 'G-B984F3PDMJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmeTUEn8NvuGC85RXbdbB-7xyz6gbm6tQ',
    appId: '1:1023285541885:android:454510dcc8c14fc99db794',
    messagingSenderId: '1023285541885',
    projectId: 'mctruckcheck',
    storageBucket: 'mctruckcheck.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx5JU75krSnZqfYMREV9hlaBPTSPTWHos',
    appId: '1:1023285541885:ios:abe874716d9734ca9db794',
    messagingSenderId: '1023285541885',
    projectId: 'mctruckcheck',
    storageBucket: 'mctruckcheck.appspot.com',
    iosBundleId: 'com.mobility.corner.app.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCx5JU75krSnZqfYMREV9hlaBPTSPTWHos',
    appId: '1:1023285541885:ios:774333ae3d3a75319db794',
    messagingSenderId: '1023285541885',
    projectId: 'mctruckcheck',
    storageBucket: 'mctruckcheck.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJoXk7jRHaQcUdZggsL7Xjf48osBd9VTo',
    appId: '1:1023285541885:web:e7342c65f7f7a7969db794',
    messagingSenderId: '1023285541885',
    projectId: 'mctruckcheck',
    authDomain: 'mctruckcheck.firebaseapp.com',
    storageBucket: 'mctruckcheck.appspot.com',
    measurementId: 'G-QMHBC9F4RE',
  );

}