// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6FhnKUtiIQ8EoyXTR3Q1fblubdQA_2DY',
    appId: '1:885253354272:web:4a851fc0599b1702349d45',
    messagingSenderId: '885253354272',
    projectId: 'fir-mobility-corner-app',
    authDomain: 'fir-mobility-corner-app.firebaseapp.com',
    storageBucket: 'fir-mobility-corner-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB92fGsRaW3TZTHZwif45o4h9jdJSgJYSc',
    appId: '1:885253354272:android:c2d2c63ea7c8558f349d45',
    messagingSenderId: '885253354272',
    projectId: 'fir-mobility-corner-app',
    storageBucket: 'fir-mobility-corner-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnZozvUordb1qpCXy68PV-yk1CT8ESsmo',
    appId: '1:885253354272:ios:dbf3da147a64fe2a349d45',
    messagingSenderId: '885253354272',
    projectId: 'fir-mobility-corner-app',
    storageBucket: 'fir-mobility-corner-app.appspot.com',
    iosBundleId: 'com.mobility.corner.app.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnZozvUordb1qpCXy68PV-yk1CT8ESsmo',
    appId: '1:885253354272:ios:9bc15a21e94fe473349d45',
    messagingSenderId: '885253354272',
    projectId: 'fir-mobility-corner-app',
    storageBucket: 'fir-mobility-corner-app.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6FhnKUtiIQ8EoyXTR3Q1fblubdQA_2DY',
    appId: '1:885253354272:web:915446f8cfb6b4e4349d45',
    messagingSenderId: '885253354272',
    projectId: 'fir-mobility-corner-app',
    authDomain: 'fir-mobility-corner-app.firebaseapp.com',
    storageBucket: 'fir-mobility-corner-app.appspot.com',
  );

}