// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD030g38UJBtq--z9cTStuN3I6MezEwUDg',
    appId: '1:25240704677:web:9fdce9902ce2327db6df4c',
    messagingSenderId: '25240704677',
    projectId: 'camion-controle-appli-v1',
    authDomain: 'camion-controle-appli-v1.firebaseapp.com',
    databaseURL: 'https://camion-controle-appli-v1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'camion-controle-appli-v1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB8XBTNbTrrfxO2L_NVmQGdNbfsnY5YTQ',
    appId: '1:25240704677:android:a43f9bdbda059a91b6df4c',
    messagingSenderId: '25240704677',
    projectId: 'camion-controle-appli-v1',
    databaseURL: 'https://camion-controle-appli-v1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'camion-controle-appli-v1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJjQX32JOuLIz5AvpCfoHDYl_eeYXQx4I',
    appId: '1:25240704677:ios:ebd56b84801ad42cb6df4c',
    messagingSenderId: '25240704677',
    projectId: 'camion-controle-appli-v1',
    databaseURL: 'https://camion-controle-appli-v1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'camion-controle-appli-v1.appspot.com',
    iosBundleId: 'com.mobility.corner.app.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJjQX32JOuLIz5AvpCfoHDYl_eeYXQx4I',
    appId: '1:25240704677:ios:706bff9215fa28ecb6df4c',
    messagingSenderId: '25240704677',
    projectId: 'camion-controle-appli-v1',
    databaseURL: 'https://camion-controle-appli-v1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'camion-controle-appli-v1.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD030g38UJBtq--z9cTStuN3I6MezEwUDg',
    appId: '1:25240704677:web:059e035d73893d5bb6df4c',
    messagingSenderId: '25240704677',
    projectId: 'camion-controle-appli-v1',
    authDomain: 'camion-controle-appli-v1.firebaseapp.com',
    databaseURL: 'https://camion-controle-appli-v1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'camion-controle-appli-v1.appspot.com',
  );

}